### ISSUE TITLE
[Bug] Game doesn't transition to round 2 @ 20180815

### ISSUE THREAD

**Issue by nathaniel-gray** [TeamVelocity/teamvelocity.github.io#17]
What: Game doesn't transition to round 2 after completion of round one
When:
- Single player game
- Round 1 completed + end of round dialog OK clicked
- Possibly important: Last spin landed on Bankrupt was last spin
![image](https://user-images.githubusercontent.com/40145468/44182121-7f5ac980-a0d3-11e8-82d5-6c82319a5a94.png)

**Comment by nathaniel-gray** [comment]
Relatedly, I played a non-edited game (3 player) through three rounds. 1 full game (2 rounds) + reset + completed game 2, round 1. The game board at completion of round 1 failed to advanced to round 2.
- No dialog box. Screen shows nothing to do.
- Attempt to spin. Dialog box shows up, and is dismissed, but scores reflect the (0,0,0) tuple from issue 18.
- Javascript error shows up (ui.js, 150): Cannot read property 'complete' of undefined

![image](https://user-images.githubusercontent.com/40145468/44188834-dc637900-a0ed-11e8-8eb4-a49bf2e55c56.png)

![image](https://user-images.githubusercontent.com/40145468/44188839-e7b6a480-a0ed-11e8-9e87-5be4eb3bc0d7.png)

**Comment by bmweiner** [comment]
I think #17, #18, and #19 are all related to the reset behavior. There is likely defect(s) somewhere in the engine or ui that are not completely reseting the game state. I would suggest that we make the reset button reload the page. This makes everything start fresh and should avoid any issues. The drawback is the player would lose the board state. I think this is acceptable since they can export, then import the board.
