### ISSUE TITLE
[Bug] Round 1 complete screen shows round 4 complete @ 20180815

### ISSUE THREAD

**Issue by nathaniel-gray** [TeamVelocity/teamvelocity.github.io#18]
Possibly related to [https://github.com/TeamVelocity/teamvelocity.github.io/issues/17]:
What: 
- Round 1 complete screen shows fact of completion but shows that round 4 (not 1) is complete
- Player score (0, 0) does not reflect the score for the round 1 (60200, 1600) - reset probably failed to clear / reset the previous game boards, and the round complete dialog failed to access the actual game index.

When:
- Reset after previous game completion
- 2 player game
- Completion of first round of 2 player game

![image](https://user-images.githubusercontent.com/40145468/44182265-42430700-a0d4-11e8-822d-a3243921abab.png)

**Comment by nathaniel-gray** [comment]
Relatedly, a normal non-edited game completing round 1 does not reflect the negative score of the players (1-3) in the round complete dialog box.

![image](https://user-images.githubusercontent.com/40145468/44188623-94902200-a0ec-11e8-93cd-957f903049b5.png)

**Comment by bmweiner** [comment]
I think #17, #18, and #19 are all related to the reset behavior. There is likely defect(s) somewhere in the engine or ui that are not completely reseting the game state. I would suggest that we make the reset button reload the page. This makes everything start fresh and should avoid any issues. The drawback is the player would lose the board state. I think this is acceptable since they can export, then import the board.
